// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOTtXW5G2YTHLu-s05mhdmWl3NTnZoSlM',
    appId: '1:1067187549080:web:5cbd586440a323787571ed',
    messagingSenderId: '1067187549080',
    projectId: 'fitkick-f9ced',
    authDomain: 'fitkick-f9ced.firebaseapp.com',
    storageBucket: 'fitkick-f9ced.appspot.com',
    measurementId: 'G-P7RS3MHLYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCa-iKhMoRV89GLpo_DfxPsAmHm4XL3D8',
    appId: '1:1067187549080:android:0917c9a03023e8c57571ed',
    messagingSenderId: '1067187549080',
    projectId: 'fitkick-f9ced',
    storageBucket: 'fitkick-f9ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKX2n91BdROC0sgndLGVvmTvA1dyhErio',
    appId: '1:1067187549080:ios:bc3d14f6180e0b867571ed',
    messagingSenderId: '1067187549080',
    projectId: 'fitkick-f9ced',
    storageBucket: 'fitkick-f9ced.appspot.com',
    iosClientId: '1067187549080-gud3quj1eeorm0ekdtlnq921pt4hgq83.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKX2n91BdROC0sgndLGVvmTvA1dyhErio',
    appId: '1:1067187549080:ios:bc3d14f6180e0b867571ed',
    messagingSenderId: '1067187549080',
    projectId: 'fitkick-f9ced',
    storageBucket: 'fitkick-f9ced.appspot.com',
    iosClientId: '1067187549080-gud3quj1eeorm0ekdtlnq921pt4hgq83.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
